pretrained_enc: 'pts_enc/'
pretrained_dec: 'pts_dec/'

# model
size_enc: 14

# data
dir_img: '/data/Flickr30k/img/'
path_ann: '/data/Flickr30k/ann/results_20130124.token'
type_attn: 'soft'

# train
dir_hub: 'hub/'
num_epoch: 100
num_batch: 64

# caption
c: 1
