pretrained_enc: "checkpoints/pretrained_enc.pth"
pretrained_dec: "checkpoints/pretrained_dec.pth"

# model
size_enc: 14

# data
dir_img: "/data/Flickr30k/img/"
path_ann: "/data/Flickr30k/ann/results_20130124.token"
type_attn: "soft"

# train
dir_hub: "./"
num_epoch: 1
num_batch: 64

# caption
c: 1
